steps:
  - name: 'europe-west1-docker.pkg.dev/connectedcars-build/cloudbuilder-wrapper/master'
    args: ['--secret-build-vars=NPM_TOKEN', '--skip-push', '--update-url=https://build-api.connectedcars.io/cloudbuilder']
    secretEnv:
      - 'NPM_TOKEN'
    env:
      - 'REPO_NAME=$REPO_NAME'
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      - 'BUILD_ID=$BUILD_ID'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'TAG_NAME=$TAG_NAME'
      - 'COMMIT_SHA=$COMMIT_SHA'
secrets:
- kmsKeyName: projects/connectedcars-staging/locations/global/keyRings/cloudbuilder/cryptoKeys/connectedcars-builder
  secretEnv:
    NPM_TOKEN: CiQAg7wCPQZ8nNz6Rmw/rMQnSJwp6egVUm+W8hubsv4ptMnPzx8SUQBefMgebGw+Lw88YICroEwuQ/v4bPpvG/argq0lEoU1033FdwNZ0Kb+jrZBRqOizn7D9JYWb4YTSCcBJV795GAEAOvz54CIX05q/e0DjoNS5A==
timeout: 3600s
